
<html>
<head link rel="rvce" href="rvce.jpg" type="image/jpg">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="shortcut icon" href="rvce.ico">
<title>Thanks!</title>
<link rel="shortcut icon" href="rvce.ico">
<link href="http://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" />
<link href="default.css" rel = "stylesheet" type="text/css" media="all">
<meta name="keywords" content="" />
<meta name="description" content="" />
</head>
<body background="rvtrans.jpg" font="Tahoma">
<center><h1 style="color:orange;">IT Infrastructure Feedback Management System</h1></center>
<center><h3>RV College Of Engineering</h3></center>
<center><h4>Bangalore-59</h4><br><br></center><br><br><br><br>
<center><h1><h1>Thank You! Your feedback is valuable to us!</h1></h1></center>
<center><a href="index.php"><b>Logout</b></a></center>
</body>
</html>